# Generated by Django 3.0.8 on 2020-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200730_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
